### ISSUE TITLE
Regression Testing of Python and Pandas Updates

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/gss-utils#138]
Regression Testing of:
- [ ] Update Pandas to v1 #48 - https://github.com/GSS-Cogs/gss-utils/issues/48
- [x] Investigate issues updating to Python 3.8 #95 - https://github.com/GSS-Cogs/gss-utils/issues/95

**Comment by canwaf** [comment]
Considering this further, I don't know how important it is once @CharlesRendle's BDD suite for databaker is delivered.

I think because I didn't have a databaker test suite when committing my Python 3.9/Pandas 1.2.0 commit I stumbled, and it even passed the GSS-COGS/gss-utils tests because none of the databaker base functionality was subject to tests. This is quite different to the testing we perform on CSV-W and CSVLint on gss-utils commits.

(Personal accountability statement: I failed at the pypd_upgrade attempt because I generally avoid using databaker for my own reasons, so I didn't think to even check the base functionality.)

If the functionality we use is tested then we won't need regression testing. What do you think @MartynBSpooner?

**Comment by MartynBSpooner** [comment]
We have another issue for the Pandas upgrade so closing this issue to provide board clarity.
