### ISSUE TITLE
Dimensions with codelists which use concepts from multiple namespaces are difficult to create and manage

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/gss-utils#210]
# Mixing codelists

There are two common scenarios we're facing:

1. A user primarily adopts an external taxonomy, but extends with their own bespoke codes, often _Unknown_ or _Total_.
2. A user mixes concepts from two or more external taxonomies (e.g., ONS statistical geographies and NUTS2, or mixing `reference.data.gov.uk/id/year/xxxx` and `reference.data.gov.uk/id/quarter/xxxx-Qx`).

_Example of 1:_
```
Geography Code
UKA
UKB
UKC
UKD
...
Unknown
Total
```

_Example of 2:_
```
Geography Code
UKA
UKB
UKC
...
E0000001
E0000002
```

In either of these cases, we have a situation where codes are coming from multiple namespaces. The `CSVW` spec doesn't provide a method of applying a URI template over a subset of the `.csv`.

Further, there is a question on how best to represent that a dimension uses concepts from several concept schemes - should a new, "super codelist" be defined locally to the dimension, or are we able to provide multiple codelists?

**Comment by rossbowen** [comment]
# Our ideal solution:

- Would avoid asking producers to place URLs into their published CSVs.
- Would retain a simple `.csv` structure and entries which, taken independently of a metadata file would look "normal" to the average person.
- Would allow producers to adopt URIs directly, rather than cluttering the URI-space and linking to external URIs through use of `owl:sameAs` or `skos:exactMatch`.

You could imagine the `CSVW` specification being extended to allow users to specify a row range over which they require a certain URI template to apply.

```json
    {
        "titles": "Geography Code",
        "name": "geography_code",
        "valueUrl": [
            { // Applies the template to rows 1 to 3,
                "@id": "http://europa.eu/{geography_code}",
                "rowrange": {
                   "min": 1,
                   "max": 3
                }   
            },
            { // Applies the template to rows 4 to 10.
                "@id": "http://ons.gov.uk/{geography_code}",
                "rowrange": {
                   "min": 4,
                   "max": 10
                }   
            }
        ]
    }
```

Some approaches which do not extend the `CSVW` spec are given below. 

## How do we use codes from multiple namespaces?

### Different namespaces, separate columns

This approach would separate data representing the same dimension into separate columns according to the namespace of the URI to be adopted.

Below, we have separated `NUTS Code` and `ONS Code` into different columns of the `.csv` as these codes come from different namespaces.

Given a `.csv` which looks like this:

| NUTS Code | ONS Code | Value |
| --------- | -------- | ----- |
| UKA       |          | 10    |
| UKB       |          | 20    |
| UKC       |          | 30    |
| ...       | ...      | ...   |
|           | E0000001 | 40    |
|           | E0000002 | 50    |

The metadata file could look something like the following. Notice the `propertyUrl` is the same for both columns.

```json
// -metadata.json
    {
        "title": "NUTS Code",
        "name": "nuts_code",
        "propertyUrl": "http://statistics.gov.uk/def/geography",
        "valueUrl": "http://europa.eu/{nuts_code}"
    },
    {
        "title": "ONS Code",
        "name": "ons_code",
        "propertyUrl": "http://statistics.gov.uk/def/geography",
        "valueUrl": "http://ons.gov.uk/{ons_code}"
    }
```

When processed with `csv2rdf`, an RDF representation would end up looking like:

```ttl
# observations.ttl

<observation> <http://statistics.gov.uk/def/geography> <http://europa.eu/UKA> ;
    <http://statistics.gov.uk/def/value> 10 ;
    .

# ...

<observation> <http://statistics.gov.uk/def/geography> <http://ons.gov.uk/E0000002> ;
    <http://statistics.gov.uk/def/value> 50 ;
    .

```

This approach trades off the usability of a `.csv` file in order to get a cleaner RDF representation. 

The approach may make a bit more sense where two external codelists are being adopted (e.g., NUTS and ONS Geographies). In the case where all codes except a `total` code belong to an external codelist, this would result in a single column whose only entry is `total` which may look strange.

The user would need to be taught to separate data into separate columns depending on the namespace.

### Coining a "bridge" URI

This approach would coin a local URI for every concept referred to in a dataset, and then use `skos:exactMatch` to relate these to the target external resources.

The producer would have two `.csv` files - one for their statistics and another which relates the codes to the target URI.

_statistics.csv_

| Geography Code | Value |
| -------------- | ----- |
| UKA            | 10    |
| UKB            | 20    |
| UKC            | 30    |
| ...            | ...   |
| E0000001       | 40    |
| E0000002       | 50    |

_codelist.csv_

| Geography Code | URI                        |
| -------------- | -------------------------- |
| UKA            | http://europa.eu/UKA       |
| UKB            | http://europa.eu/UKB       |
| UKC            | http://europa.eu/UKC       |
| ...            | ...                        |
| E0000001       | http://ons.gov.uk/E0000001 |
| E0000002       | http://ons.gov.uk/E0000002 |

A metadata file could contain details for both `.csv` files.

```json
// "url": "statistics.csv"
    {
        "title": "Geography Code",
        "name": "geography",
        "propertyUrl": "http://statistics.gov.uk/def/geography",
        "valueUrl": "http://statistics.gov.uk/data/my-dataset#{geography_code}"
    }

// -------------------------------------------------------------

// "url": "codelist.csv"
    {
        "title": "Geography Code",
        "name": "geography_code",
        "propertyUrl": "http://statistics.gov.uk/def/geography",
        "valueUrl": "http://statistics.gov.uk/data/my-dataset#{geography_code}"
    },
    {
        "title": "URI",
        "name": "uri",
        "aboutUrl": "http://statistics.gov.uk/data/my-dataset#{geography_code}",
        "propertyUrl": "skos:exactMatch",
        "valueUrl": "{uri}"
    },

```

This would result with an RDF representation like:

```ttl
# observations.ttl

<observation> <http://statistics.gov.uk/def/geography> <http://statistics.gov.uk/data/my-dataset#UKA> ;
    <http://statistics.gov.uk/def/value> 10 ;
    .

# ...

<observation> <http://statistics.gov.uk/def/geography> <http://statistics.gov.uk/data/my-dataset#E0000002> ;
    <http://statistics.gov.uk/def/value> 50 ;
    .

<http://statistics.gov.uk/data/my-dataset#UKA> skos:exactMatch <http://europa.eu/UKA> .
# ...
<http://statistics.gov.uk/data/my-dataset#E0000002> skos:exactMatch <http://ons.gov.uk/E0000002> .

```

This keeps the statistical `.csv` file clean but at the cost of not directly adopting external URIs.

### URIs in `.csv` files

A `.csv` file which initially contains codes...

| Geography Code | Value |
| -------------- | ----- |
| UKA            | 10    |
| UKB            | 20    |
| UKC            | 30    |
| ...            | ...   |
| E0000001       | 40    |
| E0000002       | 50    |

...is transformed by the user into a `.csv` file featuring URIs:

| Geography                  | Value |
| -------------------------- | ----- |
| http://europa.eu/UKA       | 10    |
| http://europa.eu/UKB       | 20    |
| http://europa.eu/UKC       | 30    |
| ...                        | ...   |
| http://ons.gov.uk/E0000001 | 40    |
| http://ons.gov.uk/E0000002 | 50    |


The metadata file indicates that whatever is present in each cell should be adopted as the URI. 

```json
// -metadata.json
    {
        "title": "Geography",
        "name": "geography",
        "propertyUrl": "http://statistics.gov.uk/def/geography",
        "valueUrl": "{geography}"
    }
```

An RDF representation would end up looking like:

```ttl
# observations.ttl

<observation> <http://statistics.gov.uk/def/geography> <http://europa.eu/UKA> ;
    <http://statistics.gov.uk/def/value> 10 ;
    .

# ...

<observation> <http://statistics.gov.uk/def/geography> <http://ons.gov.uk/E0000002> ;
    <http://statistics.gov.uk/def/value> 50 ;
    .

```

This approach trades off the usability of a `.csv` file in order to get a cleaner RDF representation. 

The user would need to be taught to include namespaces data in the data when a single column of data contains concepts from multiple namespaces.

This causes issues with the way URIs for observations are currently coined - the observation URI is made up of the entries of each cell, which when a cell contains a URI results in URIs-within-URIs.

## How do we represent a dimension with concepts from multiple codelists?

### Create a "super codelist"

A "super" concept scheme is created, with concepts from across different external codelists attached to the "super" concept scheme.

```ttl
<http://statistics.gov.uk/def/geography> a <http://purl.org/linked-data/cube#DimensionProperty> ;
    <http://purl.org/linked-data/cube#codeList> <http://statistics.gov.uk/def/concept-scheme/geography> ;
    .

<http://statistics.gov.uk/def/concept-scheme/geography> a skos:ConceptScheme ;
    owl:imports <http://europa.eu/scheme/geography> ;
    owl:imports <http://ons.gov.uk/scheme/geography> ;
    .

<http://europa.eu/UKA> skos:inScheme <http://statistics.gov.uk/def/concept-scheme/geography> .
# ...
<http://ons.gov.uk/E0000002> skos:inScheme <http://statistics.gov.uk/def/concept-scheme/geography> .

```

This would end up in many codelists being created but would facilitate the sharing of concepts. 

We would likely end up creating a load of concept schemes which extend schemes maintained elsewhere to include concepts like `unknown` or `total`, which may allow for greater sharing of concept schemes.


### Assigning multiple codelists

Multiple concept schemes are related to the dimension of interest.

```ttl
<http://statistics.gov.uk/def/geography> a <http://purl.org/linked-data/cube#DimensionProperty>;
  <http://purl.org/linked-data/cube#codeList> <http://ons.gov.uk/scheme/geography>, <http://europa.eu/scheme/geography>;
```

This approach fails [`qb:IC-19`](https://www.w3.org/TR/vocab-data-cube/#ic-19) as it is currently specified.

```sparql
ASK {
    ?obs qb:dataSet/qb:structure/qb:component/qb:componentProperty ?dim .
    ?dim a qb:DimensionProperty ;
        qb:codeList ?list .
    ?list a skos:ConceptScheme .
    ?obs ?dim ?v .
    FILTER NOT EXISTS { ?v a skos:Concept ; skos:inScheme ?list }
}

ASK {
    ?obs qb:dataSet/qb:structure/qb:component/qb:componentProperty ?dim .
    ?dim a qb:DimensionProperty ;
        qb:codeList ?list .
    ?list a skos:Collection .
    ?obs ?dim ?v .
    FILTER NOT EXISTS { ?v a skos:Concept . ?list skos:member+ ?v }
}
```

Codes which appear exclusively in one of the codelists trigger an exception for not appearing in the other codelist. 

We assume the specification intended a dimension to have _only_ one codelist, and for that codelist to be exhaustive of the codes.

**Comment by robons** [comment]
My thoughts, copied & pasted from slack:

> The CSVW spec doesn’t provide a method of applying a URI template over a subset of the .csv.
We could have two columns in the CSV, one of which contains the URI for the concept and the other which contains a unique identifier (within the mixed codelist). We could configure the info.json to use the URI column as the propertyUrl and the unique identifier column inside the aboutUrl.

The unique Identifier column could then be suppressed from output.

I don’t like the idea of partitioning by row numbers at all, that feels like it’s so each to break. And it’s great for the metadata JSON files to apply to a CSV without having to change these row number ranges.

The bridge idea (i.e. coining new codelists for every dimension of every dataset) may work well will Swirrl’s desire to shard/partition data across distinct servers.

**Comment by Robsteranium** [comment]
Thanks for the thorough treatment here @rossbowen!

## How do we use codes from multiple namespaces?

Indeed example 1 can be more pernicious than that - sometimes a new code will be introduced that actually changes the definition of other codes (notably if there was a code for "not elsewhere specified"!). In such cases it's necessary to define a new codelist and it would be nice to have a correspondence table (something we'd like to explore with XKOS but we haven't gotten that far yet).

For a similar reason, I'd be wary of a general purpose `total` or `unknown` concept as it's interpretation depends on the context. Indeed "unknown area" ought to be disjoint from "unknown period".

I have a couple of other suggestions for mixing namespaces...

### Add a namespace column

IIRC (apx 4 years ago) @mikeadams floated a v3(?) Data Baker/ WDA specification that split code identifiers into two columns. The first contained the registry (namespace) and the second the notation (reference).

This is a bit like what @robons has [suggested](https://github.com/GSS-Cogs/gss-utils/issues/210#issuecomment-801064027) but the observation dimension-value triples would have a `valueUrl` like `{+mycode_namespace}{mycode_notation}` with the `aboutUrl` using only `../mydim/{mycode_notation}/...`. You'd need to be sure that the notations didn't clash between namespaces, of course.

### CURIEs in `.csv` files

To expand on your "URIs in `.csv` files" example above...

I think you might need `"valueUrl": "{+geography}"` to prevent the `geography` value from being URI-encoded against the annotation's base URL.

I'm not sure URIs would make the csv tables _that_ much less usable. If users are e.g. joining other tables that don't provide URIs - it'd be trivial to prefix constant namespaces to the other values.

Having observation URIs with other URIs-encoded within them would work but be pretty ugly/ illegible.

If we were to generate a UUID from the dim-vals instead of using them directly then it would look cleaner ([issue on table2qb](https://github.com/Swirrl/table2qb/issues/125) and [discussion on slack](https://onswebsite.slack.com/archives/CNA5LRUUT/p1616491230214500?thread_ts=1616432090.204500&cid=CNA5LRUUT)).

An alternative might be to use CURIES, e.g. `nuts:UKA`, `gss:E0000002`. These would be more legible in cells. Sadly csvw [deliberately ignores](https://github.com/w3c/csvw/issues/866) any extensions to the json-ld `@context` but we could possibly extend our csv2rdf translator to do this. Perhaps we could even have it expand CURIEs for code-uris but treat them as strings when rendering observation-uri templates.


## How do we represent a dimension with concepts from multiple codelists?

That's an interesting finding from IC-19, I'd not noticed that before. Indeed the description in the qb spec refers to codelist-singular:

> If a dimension property has a qb:codeList, then the value of the dimension property on every qb:Observation must be in the code list. 

Indeed we could be conformant by creating a `skos:Collection` that enumerated all the codes from all the codelists (possibly with `owl:imports`).

We could even restrict this to those in use - as with `pmd:codesUsed` - defining the Dimension Property's [support](https://en.wikipedia.org/wiki/Support_(mathematics)).

You could of course then find the other codelists from the codes in that collection.

I wonder if that's a bit circuitous though? Is not the important thing that the codelists aren't (collectively) missing any dimension-values? We could just reinterpret the IC...

**Comment by mikeAdamss** [comment]
@Robsteranium - good memory 😄 

it ended up as v4 and it's how the ons cmd system operates, we had a briefing on that yesterday actually, so everyone should be familiar with the idea.

**Comment by Robsteranium** [comment]
We did a [review of 1 codelist per dimension](https://www.notion.so/swirrl/Review-of-1-codelist-per-dimension-idea-195ac7ddb2a94ca19e1f4b4775c7964e) last year and there's some other relevant points in there:

- Some hierarchies are not compatible. UK Statistical Geography hierarchies have incompatible parent-child relations - e.g. Local Authority District vs Local Authority Counties or Electoral vs Administrative schemes. A single codelist could combine resources that don't work together (you'd need to identify the relevant source schemes to understand how to interpret them).
- Dataset-specific codelists take codes out of context. Thus it wouldn't be possible to see which version of e.g. SIC codes had been used without doing an analysis to look for tell-tale codes (i.e. those that we introduced/ removed could help to triangulate the version). This is the exact problem we face with HMRC's product codes.
- Collating codes can lead to (apparent) overlaps - e.g. multiple codes just called "total" coming from distinct sub-trees. Because the sub-trees aren't necessarily MECE, the totals aren't necessarily equivalent and must be distinguished. It might be better to distinguish these by splitting the concept schemes rather than splitting the scheme into sub-trees at the first level of the hierarchy.

We could trivially conform with IC-19 by creating dataset-specific collections and leave these uncatalogued. The source schemes could have catalgoue entries and we could also declare which source-codelists were used/relevant (as these can define scope, hierarchy etc) for each cube with a property like:

```
pmdkos:codeListsUsed a rdf:Property
  rdfs:domain qb:ComponentSpecification; # or possibly qb:DimensionProperty
  rdfs:range skos:ConceptScheme;
```

More generally I'm concerned that we're making it harder to link data and that we risk deferring harmonisation indefinitely. Dataset-specific codelists are not as valuable as common ones. If we're not attempting to re-use and harmonise codes then we'll see a proliferation of single-use codelists and isolated cubes. This will likely further delay harmonisation. I'd be happier with transient disharmony if we had a strategy for resolving it!

**Comment by ajtucker** [comment]
> ### CURIEs in `.csv` files
> To expand on your "URIs in `.csv` files" example above...

Pushing on this a little, while as you mention it's not currently possible due to the restriction on `@context` disallowing new prefixes, @rossbowen [pointed to an example in the CSV-W spec](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#:~:text=table%20with%20compact%20urls%20and%20micro%20syntax) that uses compact URIs for values, though obviously using one of the built-in prefixes (foaf).

It's notable that the corresponding URI template in this example misses out the required `+` value modifier, i.e. the URI template should be `{+project_type}`.

If we were to allow some flexibility in the `@context` definition for CSV-W, I reckon something like the following would allow us to use compact URIs in CSVs:

| Geo Code     | Value | 
|--------------|-------| 
| nuts:UKA     | 10    | 
| nuts:UKB     | 20    | 
| nuts:UKC     | 30    | 
| ons:E0000001 | 40    | 
| ons:E0000002 | 50    | 

```json
{
  "@context": [
    "http://www.w3.org/ns/csvw",
    {
      "@language": "en",
      "ons": "http://statistics.data.gov.uk/id/statistical-geography/",
      "nuts": "http://data.europa.eu/nuts/code/"
    }
  ],
  "tables": [
    {
      "url": "obs.csv",
      "tableSchema": {
        "columns": [
          {
            "name": "geo",
            "titles": "Geo Code",
            "propertyUrl": "http://statistics.gov.uk/def/geography",
            "valueUrl": "{+geo}"
          },
          {
            "name": "value",
            "titles": "Value",
            "datatype": "int",
            "propertyUrl": "http://example.com/measure#count"
          }
        ],
        "aboutUrl": "http://example.com/{+geo}"
      }
    }
  ]
}
```

Note that the above rightly fails in the current version of `csv2rdf`, though the JSON does parse as JSON-LD and the prefixes are used properly.

**Comment by ajtucker** [comment]
We've now had time to explore a few different approaches in practice and unfortunately they're all a bit unappealing.

In addition to [Ross' original comment](https://github.com/GSS-Cogs/gss-utils/issues/210#issuecomment-801059134), a key requirement is to validate Tidy CSV files using foreign key constraints, and this has lead to [exploring a common schema for both simple codelists and also mixed codelists](https://github.com/GSS-Cogs/family-schemas/issues/3).

I'm now coming around to the idea of having a separate "bridging" table but using `owl:sameAs` to associate the codes/notations used in a Tidy CSV with existing SKOS concepts and then doing some post processing on the output from `csv2rdf` to replace (local) URIs with their existing SKOS concept URI.

So as in the above 'Coining a "bridge" URI' but using `owl:sameAs` rather than `skos:exactMatch` and then a filter to replace URIs.

**Comment by rossbowen** [comment]
I've done some further workings of bridge uri stuff using `owl:sameAs` and post-processing [here](https://github.com/GSS-Cogs/bridge-uri-example).

**Comment by Robsteranium** [comment]
I don't think that validating foreign key constraints should be treated as a vital requirement.

I think the resources within the csvw should be able to refer to external resources. Not everything needs to be described within the table group. Further not every resource needs to be in csvw. Ultimately we can only check referential integrity in a wider context (e.g. the triplestore).

Checking this earlier in the pipeline is preferable of course but not the only option and not a requirement that should dictate how we model the data. This isn't just about post processing bridge tables in RDF (how would tabular users exploit that?) but also about harmonisation more broadly.

**Comment by canwaf** [comment]
We're looking at creating resources now in gss-cogs/csvcubed#44, which will at least provide a slightly more explicit way of creating code lists manually (and thus be able to mix and match concepts across concept schemes). Since this won't be addressed in gss-utils directly, I'm closing this issue with a cross reference to csvcubed.

**Comment by canwaf** [comment]
Reopening with label:question at request of @robons.
