### ISSUE TITLE
CSV-W from separate column mapping

### ISSUE THREAD

**Issue by IeuanMan** [GSS-Cogs/gss-utils#22]
When doing a data transformation, we want to be able to express some mapping between column names and URIs such that the transform can be isolated from others and the registry of dimensions and codelists.

See https://github.com/GSS-Cogs/gss-utils/blob/csvw_from_mapping/features/csvw.feature

**Comment by ajtucker** [comment]
We want to separate out the concerns of transforming source data (spreadsheets) into tidy data from the concerns around managing reference data (dimensions, codelists).

The transformed Tidy CSV should use the obvious column names from the source data (e.g. Country) and while the transformation notebook needs to use "codes" for the values of cells, it needs to keep track of the mapping between the codes and the labels used in the source data -- the codelists.

We need to decouple these concerns so that the transformation notebook can be worked on independently from the reference data management work.

The relation between the two can be declared in the `info.json` file as a mapping between column titles and the info required to generate the CSVW transformation.

See https://github.com/GSS-Cogs/family-trade/blob/robust-transforms/datasets/ONS-UK-trade-in-goods-by-industry-country-and-commodity/info.json

**Comment by ajtucker** [comment]
The initial version of this is now merged into the main branch of gss-utils for testing.

The mapping between CSV column names and dimensions/values can be provided as a JSON document, normally in the `info.json` file.

The next version of this will need to allow for multi-measures and a measure-type column, better handle "local" dimensions and codelists, use a registry for validation and further definition if necessary, add schema constraints.
