### ISSUE TITLE
ONS metadata comments/descriptions

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#238]
https://github.com/Swirrl/cogs-issues/issues/237 identifies some issues with comments and descriptions from the ONS `/data.json`.

**Comment by mikeAdamss** [comment]
could you replicate the comments over here please Alex (don't have access to that)

**Comment by ajtucker** [comment]
> could you replicate the comments over here please Alex (don't have access to that)

Sure, sorry. The issue is that https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk-catalog-entry shows an overly long description with markdown.

The [Epic](https://github.com/GSS-Cogs/gss-utils/issues/85) for this is to go through all the scrapers and make sure we're getting the `rdfs:comment` and `dct:description` fields right, along with using a special property for Markdown descriptions (see the metadata docs linked in the Epic).

The best bet here is to create an issue branch for this and add some BDD specifically for this dataset to check that the metadata we populate is right wrt. that revised metadata doc. That may break some of the other BDD tests, which we'll need to refactor and then may need to refactor the code in other scrapers!

**Comment by rossbowen** [comment]
So this looks to be displaying correctly to me on `beta` but I think that's because of some massaging of the data which has gone on.

For the mentioned dataset, [this](https://github.com/GSS-Cogs/family-trade/blob/c2b42ac95922169dce57e91f88bea19b0839fefd/datasets/ONS-International-exports-of-services-from-subnational-areas-of-the-UK/main.py#L336-L355) looks to be the offending line, `comment` should be a short description which appears on the catalog page. `description` is not currently displayed anywhere.

In general, a quick review of the ONS scraper shows where stuff is populated from.

https://github.com/GSS-Cogs/gss-utils/blob/9fbc742ecd713e281d766a89681bc56b9a2211f6/gssutils/scrapers/ons.py#L51

https://github.com/GSS-Cogs/gss-utils/blob/9fbc742ecd713e281d766a89681bc56b9a2211f6/gssutils/scrapers/ons.py#L61-L64

Taking a typical dataset with `type = dataset_landing_page`, we get:

```python
import requests
url = "https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/datasets/uktradeallcountriesseasonallyadjusted/data"
r = requests.get(url).json()

r["description"]["metaDescription"]
#> 'The annual and monthly goods export and import figures for all countries of the UK. '

r["description"]["summary"]
#> 'The annual and monthly goods export and import figures for all countries with the UK.'
```

I did this for a few datasets and found the `metaDescription` and `summary` always matched (except for the whitespace at the end!) These are typically short so I reckon are fine to keep as is.

Then for an ad-hoc, so `type = static_adhoc` (the only [other page type the scraper will process](https://github.com/GSS-Cogs/gss-utils/blob/9fbc742ecd713e281d766a89681bc56b9a2211f6/gssutils/scrapers/ons.py#L43)):

```python
url = "https://www.ons.gov.uk/economy/economicoutputandproductivity/output/adhocs/13524businessinsightsandconditionssurveybicswave33adhoctablesdepartmentfortransport/data"

r = requests.get(url).json()

r["markdown"][0]
#> 'Ad Hoc tables for the Department for Transport. The weighted table included is a crosstab of returning to work questions that was not published in the weighted Business Insights and Conditions Survey (BICS) Wave 33 results. \n\nThe sample design for BICS was reviewed and refreshed in Wave 17 and will be the basis for future waves.  This sample redesign improves our coverage for the smaller sized businesses. \n\nThe survey was sent to around 39,000 UK businesses, and results presented in this release are based on a limited number of responses, around 25.0% (9,645) of all businesses surveyed who responded.\n\n### Contact\nFor more information on this request please email <bics@ons.gov.uk>.'
```

The ad-hoc descriptions end up being a bit longer, potentially too long to make for a good `comment`. There's no alternative metadata available to make a good `comment` so I suppose we could do something like trying to extract the first line. Also, `r["description"]["metaDescription"] = ""` so you end up with a blank `dcat:description`.

**Comment by rossbowen** [comment]
I think I've addressed the issues specifically with the ONS scraper so think I can close this. 

There's some more work to do on the associated epic (https://github.com/GSS-Cogs/gss-utils/issues/85) to get descriptions appearing in PMD and make sure the GOVUK scraper is also populating this stuff correctly but will handle that there.
