### ISSUE TITLE
Log out the (metdata) contents of the scraper used to /out

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#282]
on Jenkins when a pipeline runs. Implement a means to pass these files in to Scraper() (so we can "pin"a pipeline to an old scrape if needed).

**Comment by ajtucker** [comment]
If we're thinking along similar lines, then the way I want to do something similar to pinning data is to make use of VCR.py to make a record of the responses from external websites so that we can use these as fixtures while developing and testing a pipeline. The idea is to help us do continuous integration on master/main without things breaking because upstream pages or data changes. See GSS-Cogs/family-trade#196

**Comment by mikeAdamss** [comment]
closing this, we've already got cards for this sorta thing.
