### ISSUE TITLE
Add new SPEC 1 output code into GSSUtils

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/gss-utils#69]
Integration with Tracer

Pre-requisite - review of Leigh's draft SPEC 1

- [x] Implementation (2-3 days).
- [ ] TDD Test (2-3 days depending on coverage).
- [x] Spec - JSON structure etc.
- [x] Deploy onto Docker

**Comment by mikeAdamss** [comment]
starting with the Spec function notes here: https://sites.google.com/d/1KKMMxOcIVHFqdPLh4dc8g2USVRpbKoPk/p/10IbCW3aNzyj640UiUz95z8ET8pwq0LmG/edit?pli=1&authuser=1

We need to incorporate the functionality described into the gss-utils transformTrace class.

The tracer _should_ already hold the information already, so we need to tap into it and output the markdown, i.e get to the same place but "under the hood" rather than bringing more functions into the transform scripts.

probably need to add an additional keyword argument to existing api, i.e `tracer.output(update_spec=True)`, that'll let us keep backwards compatibility.

**Comment by mikeAdamss** [comment]
Have added tests as a separate issue as we put them out of scope.
